#!/bin/bash
#SBATCH --job-name=gamess_batch
#SBATCH --output=gamess-batch-%j.out
#SBATCH --error=gamess-batch-%j.err
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --gpus-per-node=4
#SBATCH --account=m4265_g
#SBATCH --qos=regular
# #SBATCH --constraint=gpu&hbm80g
#SBATCH --constraint=gpu



# Load required modules
module load PrgEnv-nvidia
module load cmake

export OMP_NUM_THREADS=63
# export OMP_PLACES=cores
# export OMP_PROC_BIND=spread

# Loop over subdirectories and run GAMESS in each
for dir in *; do

    cd "$dir" || continue


    for input_file in *.inp; do

	log_file="${input_file%.inp}.log"
        
        # Skip if log file already exists
        if [[ -f "$log_file" ]]; then
            echo "Skipping $input_file in $dir – $log_file already exists."
            continue
        fi

    	echo "Running $input_file in $dir at $(date)"
        /global/homes/d/delangel/gamess_liberi_cmake_benchmark/rungms-dev "$input_file" 00 1 &> $log_file 
        echo "Finished $input_file in $dir at $(date)"
    done

    cd ..

done

